README.md
=> Updates installation to mention NPM package

CHANGELOG.md, README.md, package.json
Adds a CHANGELOG.md, includes descriptions of server-side rendering and
a note so that I don't forget again about npm link.
=> Release bump for v1.0.1

CHANGELOG.md, README.md, demo/app.js, demo/index.html, package.json, velocity-component.js, velocity-transition-group.js
Fix for #17. Thanks to @jmfurlott for the PR this was based on.
Also adds in note about `npm dedupe` to the README.
=> Updates to React 0.14

README.md, demo/components/box.jsx, demo/components/loading-crossfade-component.jsx, demo/examples/flap-box.jsx, demo/examples/scrolling-group.jsx, demo/examples/toggle-box.jsx, demo/examples/trigger-box.jsx, velocity-component.js
Just a few misspellings/nits I found while verifying/working on a bug!
=> Fix few typos and some cleanup

README.md
Based on feedback from @basrat in #42.
=> Mentions Velocity UI Pack in Installation section

velocity-transition-group.js
Avoids squashing the Velocity complete handlers for
VelocityTransitionGroup.
See #20
=> Complete handlers for VelocityTransitionGroup

README.md
This has confused enough people.
=> Clean up language around server-side rendering

velocity-transition-group.js
=> Shim window.requestAnimationFrame for browsers that don't support it

velocity-transition-group.js
The default display: none / display: '' is not appropriate in some cases
where the geometry of the entering element must be calculated as it
appears in the DOM. The new enterHideStyle and enterShowStyle props can
be used to override this default.
=> Allows for an alternate enter hide/show strategy

package.json
Switches to React 15 for the demo.
Thanks to @StevenLangbroek for the original PR.
=> Updates to support React 15

velocity-transition-group.js
Sends any scope and arguments set by Velocity into the complete callback
on VelocityTransitionGroup animations.
=> Passes this and arguments to complete function

README.md
=> update README with demo link

README.md
Finally Velocity.js got his own domain!
=> Fix paths to Velocity docs (again)

lib/velocity-animate-shim.js
this pull request is try to fix the this [issus](https://github.com/twitter-fabric/velocity-react/issues/119)
=> enable server test with window

lib/velocity-animate-shim.js
Also changes the jsdom check to be more specific to jsdom, rather than
looking at the NODE_ENV.
=> Adds removeData to server/test shim

lib/velocity-animate-shim.js
Going with @domenic's suggestion from:
https://github.com/tmpvar/jsdom/issues/1537
=> Fix mis-implementation of jsdom check

lib/velocity-animate-shim.js
To fix #131 by switching to String.prototype.indexOf instead of String.prototype.includes
=> Switch to use String.prototype.indexOf instead of String.prototype.includes

README.md, package.json
`prop-types` [requires](https://github.com/reactjs/prop-types#compatibility) `React 0.14.9` or `React ^15.3.0`
=> Fix peerDependencies to be compatible with prop-types package

CHANGELOG.md, README.md, package.json, src/velocity-transition-group.js
=> 1.3.3 release with fix for timer clearing

.eslintignore, .eslintrc, demo/app.js, demo/webpack.config.js, package-lock.json, package.json, src/lib/velocity-animate-shim.js, src/velocity-component.js, src/velocity-helpers.js, src/velocity-transition-group.js
Includes package-lock.json from npm 5.
=> Adds linting, prettier

CHANGELOG.md, README.md, package.json, src/velocity-transition-group.js
=> Adds guard against falsey children

CHANGELOG.md, README.md, package-lock.json, package.json, src/velocity-transition-group.js
- Uses a no-op Transition element to consume TransitionGroup’s props
- Updates some dependencies per npm audit (remaining issues are
dev-only)
=> 1.4.2 Update
