google-fabric/velocity-react

package.json
Removes the peerDependencies warning for the demo.
=> Require babel-core explicitly

lib/velocity-animate-shim.js, velocity-component.js, velocity-helpers.js, velocity-transition-group.js
Keeps us from trying to run Velocity animations when the component is
being rendered on the server. Not an ideal server-side solution, but
reasonably good for a lot of use cases.
=> Shims out Velocity on the server

README.md
The README lists the helper's name as `velocityHelper`, but in the code its `velocityHelpers`.
Just a quick fix :).
=> update README with actual helper name

lib/velocity-animate-shim.js
without this, velocity-react was always requiring a new instance of velocity-animate, so require('velocity-animate/velocity-ui') was attaching to the wrong instance. This finds an existing instance the correct way (the same way velocity.ui.js does it)
=> use the existing instance of Velocity instead of requiring a new one

CHANGELOG.md, README.md, package.json, velocity-transition-group.js
Refactor into "_shortCircuitAnimation" failed to account for difference
between enter and leave.
Updates everything for a v1.1.1 release.
=> Fixes VelocityTransitionGroup for no "leave"

velocity-helpers.js
No-ops velocityHelpers.registerEffect if our Velocity server-side shim
is in place. Allows it to return a value but doesn't try to register it
with the non-existant Velocity.
See #44
=> Allow registerEffect to run on the server

velocity-transition-group.js
I kept getting an 'Invalid calling object' error in IE 10+ whenever `shimRequestAnimationFrame()` was called. Binding the method to `window` seems to fix it.
=> FIx 'Invalid calling object' error in IE when trying to invoke shimRequestAnimationFrame

package.json
Just updating the links in the package.json to point to the current twitter-fabric urls.
=> Update crashlytics references to twitter-fabric

README.md
=> Clarifies that VelocityComponent has only one child, not children

README.md
Just missing the other backtick :wink:
=> Fix README typo: TransitionGroup`

velocity-helpers.js
SystemJS is trying to do a real require with this error string, which is only informational. This will fix the problem.
This is the issue with more info about the problem: https://github.com/systemjs/systemjs/issues/1417
=> Change require string in error to fix SystemJS import

velocity-component.js, velocity-transition-group.js
Without jQuery, velocity implements it's own `$.data()` utility which
stores element (animation) data in one big cache object.
Data in this cache is never cleared which is an issue because it keeps
references to all animated dom elements as well as whole React trees
through velocity-react's `complete` handler.
This commit crudely clears the most important velocity data when an
animated component is unmounted.
See julianshapiro/velocity#644
Otherwise, this leak causes constant crashes for non-trivial webapps on mobile devices.
=> Fix memory leaks

package.json
1.3.0 has no breaking changes according to their README (just code cleanup), and 1.3.1 contains a race condition fix for an error that we saw in production (https://github.com/julianshapiro/velocity/pull/690). 1.3.1 is the current latest version.
=> Bump velocity-animate to 1.3.1

CHANGELOG.md, README.md, package.json
Just doing a patch bump since 1.3.1 of `velocity-animate` doesn't have any breaking changes, just code cleanup and a few bug fixes.
=> Release bump for 1.1.9

package.json
Reverts twitter-fabric/velocity-react#135
1.3.1 isn't published to npm yet :(
=> Revert "Bump velocity-animate to 1.3.1"

lib/velocity-animate-shim.js
Checking for `navigator` (in addition to window) allows for usage in webpack when rendering on the server.
=> Check for navigator before checking its properties.

velocity-component.js
this is a bug that seems to cause an error when certain components re-render, at least for my app. surely it's a typo that the _. is missing?
=> fix undefined forEach method

velocity-component.js
Added the `interruptBehavior` prop. Depending on this prop, the animation will be stopped, or jump to the finish. You can leave it empty and it will just queue the animation.
Related to issue #185
=> Added interruptBehavior

src/velocity-transition-group.js
IE8 throws "Object doesn't support this property or method" on shimCancelAnimationFrame.bind(window)
=> IE8's clearTimeout is not a function

package.json
`react-transition-group` [requires](https://github.com/reactjs/react-transition-group/blob/master/package.json#L41-L42) `React ^15.0.0`
=> Fix peerDependencies to be compatible with the 'react-transition-group' package

README.md
Link to demo in readme points to old twitter link. Updated to google link
=> Update Live Demo link from twitter to googe

CHANGELOG.md, README.md, demo/examples/scrolling-group.jsx, demo/examples/toggle-box.jsx, demo/examples/trigger-box.jsx, demo/main.jsx, demo/webpack.config.js, package-lock.json, package.json, src/velocity-component.js, src/velocity-helpers.js, src/velocity-transition-group.js
- Changes our `componentWillUpdate` call to `componentDidUpdate` to eliminate a
React 16.3 StrictMode warning
- Migration to [react-transition-group](https://github.com/reactjs/react-transition-group) v2
- Switches from lodash 3 to lodash 4
- Changes demo to use React 16.3
Also, removes `react-tween-state` because it was contributing to a
potential memory leak in the demo.
Fixes #237, fixes #236, fixes #235, fixes #229, fixes #222, fixes #224
Closes #233
=> v1.4.0 dependency updates

demo/main.jsx, src/velocity-transition-group.js
Avoids needing to polyfill for IE11.
Also removes <StrictMode> from the demo, since that also doesn't work on
IE 11 without a polyfill.
=> Removes Promise dependency
